sudo: false
language: node_js
node_js:
  - 10
script:
  - npm run build && npm run generate-docs && cd dist

deploy:
  - provider: npm
    api_key: $NPM_TOKEN
    email: ezain2t@gmail.com
    skip_cleanup: true
    on:
      tags: true
      repo: eboukamza/finlambda
  - provider: releases
    skip_cleanup: true
    api_key: $GH_TOKEN
    on:
      tags: true
      repo: eboukamza/finlambda
  - provider: pages
    local_dir: docs
    repo: eboukamza/finlambda-docs
    skip_cleanup: true
    keep-history: true
    github_token: $GH_TOKEN
    target-branch: master
    committer-from-gh: true
    on:
      tags: true
      repo: eboukamza/finlambda
