sudo: false
language: node_js
node_js:
  - 10
script:
  - npm run build
after_script:
  - cd dist

deploy:
  - provider: npm
    api_key: $NPM_TOKEN
    email: ezain2t@gmail.com
    skip_cleanup: true
    on:
      tags: true
      repo: eboukamza/finlambda
  - provider: releases
    skip_cleanup: true
    api_key: $GH_TOKEN
    on:
      tags: true
      repo: eboukamza/finlambda
